### PR TITLE
Add ready manifest to pre-round lobby

### PR DESCRIPTION
**Pull request by 12rabbits**
Adds a new openable UI element to the lobby that tracks how many players are readied up for each job. Core functionality is complete, but it could still use some cleanup in the future for better efficiency.

Tracks high priority for all jobs except for Command, which checks for any priority. 

## Why / Balance

Was suggested by some people on the forum. Should help to avoid under-staffed departments at round start. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a ready manifest display to the pre-round lobby.

### CODE REVIEW

**Comment by Pivotbash** [comment]
Hey, hoping to get your attention with a comment. Upstream has expressed interest in getting this PRd to them, which would be a favor to both them and to DV, or if you wanted to give permission for someone on impstation to PR it for you, I'm pretty sure that works copyright wise.

**Comment by 12rabbits** [comment]
Sure, I'd be down to port it myself! Definitely need to clean it up a bit first, I can get started on that soon.

**Comment by Pivotbash** [comment]
Hell yeah, thank you!

**Comment by Coolsurf6** [comment]
Hey 12rabbits. I wanted to ask since I played on harmony recently which had ported your changes from https://github.com/ss14-harmony/ss14-harmony/pull/514.

I wanted to ask if you still wanted to try bringing this to upstream. I was going to ask for licensing to move this to MIT, so I could try and port this to Umbra, and probably Cosmetic Drift first (we are a downstream of Cosmetic Drift). But I always want to try and give content to the most amount of people. Some HRP stuff makes sense to keep on HRP, but this was such an amazing addition that I fell in love with it for the singular minute I got to see it before Harmony closed :P

If you want, could I get in contact with you on Discord if you wanted to discuss. I would be happy to try and learn how to help port this, as the porter from Harmony expressed that they were fine with me porting their changes they made on Harmony, but I needed to go to the original creator, aka yourself!

**Pull request merged**
